/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author jaisi
 */


import AppPackage.AnimationClass;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.URI;
import java.nio.file.Files;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {

    private Register r;
    private Mostrar mostrar;
    static JFrame current;
    private String tps;
    static boolean logged;
    private NodeBS nodoRaiz;

    /**
     * Constructor default de la clase
     */
    
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        logged = false;
        r = new Register();
        jPanel1.requestFocus();
        tps = passField.getText();
    }

    public void openInternet(String url) {
        try {
            Desktop.getDesktop().browse(URI.create(url));
        } catch (IOException e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpIngreso = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mailField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        passField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        lblInternet = new javax.swing.JLabel();
        lblMusica = new javax.swing.JLabel();
        registrarseLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        reporteB = new javax.swing.JLabel();
        agregarTareaB = new javax.swing.JLabel();
        generarTxtB = new javax.swing.JLabel();
        observarB = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        flagSession = new javax.swing.JLabel();
        cerrarSesionB = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cerrarButton = new javax.swing.JLabel();
        minimizarButton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpIngreso.setBackground(new java.awt.Color(255, 255, 255));
        jpIngreso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jpIngreso.setForeground(new java.awt.Color(255, 255, 255));
        jpIngreso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpIngresoMouseClicked(evt);
            }
        });
        jpIngreso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(238, 112, 82));
        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(238, 112, 82));
        jLabel2.setText("Password:");
        jpIngreso.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jLabel3.setBackground(new java.awt.Color(238, 112, 82));
        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(238, 112, 82));
        jLabel3.setText("Email");
        jpIngreso.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_User_96px_2.png"))); // NOI18N
        jpIngreso.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 100, 100));

        mailField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        mailField.setForeground(new java.awt.Color(153, 153, 153));
        mailField.setText("Ingrese email");
        mailField.setBorder(null);
        mailField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mailFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                mailFieldFocusLost(evt);
            }
        });
        mailField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mailFieldMouseExited(evt);
            }
        });
        jpIngreso.add(mailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 180, 30));
        jpIngreso.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 220, 20));
        jpIngreso.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 292, 220, 20));

        passField.setForeground(new java.awt.Color(153, 153, 153));
        passField.setText("jPasswordField1");
        passField.setBorder(null);
        passField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passFieldFocusLost(evt);
            }
        });
        jpIngreso.add(passField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 180, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_customer_32px_1.png"))); // NOI18N
        jLabel1.setToolTipText("");
        jpIngreso.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 30, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Key_32px.png"))); // NOI18N
        jpIngreso.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 40, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Menu_32px.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jpIngreso.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        loginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Enter_OFF.png"))); // NOI18N
        loginButton.setBorderPainted(false);
        loginButton.setContentAreaFilled(false);
        loginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Enter_ON.png"))); // NOI18N
        loginButton.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Enter_ON.png"))); // NOI18N
        loginButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Enter_ON.png"))); // NOI18N
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        jpIngreso.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 110, 40));

        lblInternet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Globe_32px.png"))); // NOI18N
        lblInternet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInternetMouseClicked(evt);
            }
        });
        jpIngreso.add(lblInternet, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 80, -1, 30));

        lblMusica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Musical_Notes_32px.png"))); // NOI18N
        lblMusica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMusicaMouseClicked(evt);
            }
        });
        jpIngreso.add(lblMusica, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 120, -1, -1));

        registrarseLabel.setBackground(new java.awt.Color(255, 99, 71));
        registrarseLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        registrarseLabel.setForeground(new java.awt.Color(255, 99, 71));
        registrarseLabel.setText("Registrarse");
        registrarseLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registrarseLabelMouseClicked(evt);
            }
        });
        jpIngreso.add(registrarseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 495, -1, -1));

        getContentPane().add(jpIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 580));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reporteB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reporteB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/analytics128.png"))); // NOI18N
        reporteB.setEnabled(false);
        reporteB.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                reporteBMouseMoved(evt);
            }
        });
        reporteB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reporteBMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reporteBMouseExited(evt);
            }
        });
        jPanel1.add(reporteB, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 180, 130));

        agregarTareaB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agregarTareaB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/addTarea128.png"))); // NOI18N
        agregarTareaB.setEnabled(false);
        agregarTareaB.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                agregarTareaBMouseMoved(evt);
            }
        });
        agregarTareaB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarTareaBMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                agregarTareaBMouseExited(evt);
            }
        });
        jPanel1.add(agregarTareaB, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 180, 150));

        generarTxtB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        generarTxtB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/txt128.png"))); // NOI18N
        generarTxtB.setEnabled(false);
        generarTxtB.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                generarTxtBMouseMoved(evt);
            }
        });
        generarTxtB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                generarTxtBMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                generarTxtBMouseExited(evt);
            }
        });
        jPanel1.add(generarTxtB, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 180, 150));

        observarB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        observarB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/observar128.png"))); // NOI18N
        observarB.setEnabled(false);
        observarB.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                observarBMouseMoved(evt);
            }
        });
        observarB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                observarBMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                observarBMouseExited(evt);
            }
        });
        jPanel1.add(observarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 180, 150));

        jLabel13.setBackground(new java.awt.Color(255, 99, 71));
        jLabel13.setForeground(new java.awt.Color(255, 99, 71));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Agregar tarea");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 80, 20));

        jLabel14.setBackground(new java.awt.Color(255, 99, 71));
        jLabel14.setForeground(new java.awt.Color(255, 99, 71));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Observar");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 70, 20));

        jLabel16.setBackground(new java.awt.Color(255, 99, 71));
        jLabel16.setForeground(new java.awt.Color(255, 99, 71));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Generar .txt");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, 100, -1));

        jLabel17.setBackground(new java.awt.Color(255, 99, 71));
        jLabel17.setForeground(new java.awt.Color(255, 99, 71));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Reporte ");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 70, -1));

        flagSession.setBackground(new java.awt.Color(255, 99, 71));
        flagSession.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        flagSession.setForeground(new java.awt.Color(255, 99, 71));
        flagSession.setText("No se ha iniciado sesión");
        jPanel1.add(flagSession, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, -1, -1));

        cerrarSesionB.setBackground(new java.awt.Color(255, 255, 255));
        cerrarSesionB.setForeground(new java.awt.Color(0, 0, 0));
        cerrarSesionB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout16.png"))); // NOI18N
        cerrarSesionB.setText("Cerrar Sesión");
        cerrarSesionB.setEnabled(false);
        cerrarSesionB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionBActionPerformed(evt);
            }
        });
        jPanel1.add(cerrarSesionB, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 530, 530));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cerrarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Multiply_32px.png"))); // NOI18N
        cerrarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarButtonMouseClicked(evt);
            }
        });
        jPanel2.add(cerrarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 30, 30));

        minimizarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Expand_Arrow_32px.png"))); // NOI18N
        minimizarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizarButtonMouseClicked(evt);
            }
        });
        jPanel2.add(minimizarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 40, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 540, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        AnimationClass internet = new AnimationClass();
        internet.jLabelXRight(-40, 10, 10, 5, lblInternet);

        AnimationClass musica = new AnimationClass();
        musica.jLabelXRight(-40, 10, 10, 5, lblMusica);

        //<---
        AnimationClass internett = new AnimationClass();
        internett.jLabelXLeft(10, -40, 10, 5, lblInternet);

        AnimationClass musicaa = new AnimationClass();
        musicaa.jLabelXLeft(10, -40, 10, 5, lblMusica);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void minimizarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarButtonMouseClicked
        this.setState(Login.ICONIFIED);
    }//GEN-LAST:event_minimizarButtonMouseClicked

    private void cerrarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarButtonMouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "¿Desea salir del programa?", "Exit", dialog);
        if (result == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_cerrarButtonMouseClicked

    private void agregarTareaBMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarTareaBMouseMoved
        agregarTareaB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(163, 163, 163)));
    }//GEN-LAST:event_agregarTareaBMouseMoved

    private void agregarTareaBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarTareaBMouseExited
        agregarTareaB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_agregarTareaBMouseExited

    private void observarBMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_observarBMouseMoved
        observarB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(163, 163, 163)));
    }//GEN-LAST:event_observarBMouseMoved

    private void observarBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_observarBMouseExited
        observarB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_observarBMouseExited

    private void reporteBMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reporteBMouseMoved
        reporteB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(163, 163, 163)));
    }//GEN-LAST:event_reporteBMouseMoved

    private void reporteBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reporteBMouseExited
        reporteB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_reporteBMouseExited

    private void generarTxtBMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generarTxtBMouseMoved
        generarTxtB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(163, 163, 163)));
    }//GEN-LAST:event_generarTxtBMouseMoved

    private void generarTxtBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generarTxtBMouseExited
        generarTxtB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_generarTxtBMouseExited

    private void lblInternetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInternetMouseClicked
        openInternet("http://guaymaro.uninorte.edu.co/UNEspacio/index.php?p=Index");
    }//GEN-LAST:event_lblInternetMouseClicked

    private void lblMusicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMusicaMouseClicked
        openInternet("https://open.spotify.com/browse");
    }//GEN-LAST:event_lblMusicaMouseClicked

    private void registrarseLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarseLabelMouseClicked
        current = this;
        current.setVisible(false);
        r.setVisible(true);
    }//GEN-LAST:event_registrarseLabelMouseClicked

    private void mailFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mailFieldFocusGained
        if (mailField.getText().equals("Ingrese email")) {
            mailField.setText("");
        }
    }//GEN-LAST:event_mailFieldFocusGained

    private void mailFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mailFieldFocusLost
        if (mailField.getText().equals("Ingrese email")) {
            mailField.setText("Ingrese email");
        }
    }//GEN-LAST:event_mailFieldFocusLost

    private void passFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passFieldFocusGained
        if (passField.getText().equals(tps)) {
            passField.setText("");
        }
    }//GEN-LAST:event_passFieldFocusGained

    private void passFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passFieldFocusLost
        if (passField.getText().equals(tps)) {
            passField.setText(tps);
        }
    }//GEN-LAST:event_passFieldFocusLost

    private void mailFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mailFieldMouseExited
    }//GEN-LAST:event_mailFieldMouseExited

    private void jpIngresoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpIngresoMouseClicked
        jpIngreso.requestFocus();
    }//GEN-LAST:event_jpIngresoMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        jPanel1.requestFocus();
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        jPanel2.requestFocus();
    }//GEN-LAST:event_jPanel2MouseClicked

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed

        try {
            String user = mailField.getText();
            char[] arrayC = passField.getPassword();
            String trypass = new String(arrayC);
            
            int res = Validations.validateData(user, trypass);
            if (res == 1) {
                loginActions(user, true);
            } else if (res == 2) {
                JOptionPane.showMessageDialog(null, "Email y/o password incorrectos");
            }
            mailField.setText("Ingrese email");
            passField.setText(tps);
        } catch (Exception ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void agregarTareaBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarTareaBMouseClicked
        if(agregarTareaB.isEnabled()){
            String [] name = flagSession.getText().split("@uninorte.edu.co");
            File temp = new File("files\\"+name[0]);
            if(temp.exists()){
                try {
                    temp = new File("files\\"+name[0]+"\\"+name[0]+"_info.txt");
                    NodeBS root = NodeBS.fileToTree(temp);
                    Tareas t = new Tareas(root,name[0]);
                    current= this;
                    t.setVisible(true);
                    current.setVisible(false);
                } catch (Exception ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else{
                current = this;
                this.setVisible(false);
                StartProyect sp = new StartProyect(name[0]);
                sp.setVisible(true);
                
            }
            
        }
    }//GEN-LAST:event_agregarTareaBMouseClicked

    private void observarBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_observarBMouseClicked
        if(observarB.isEnabled()){
            String [] name = flagSession.getText().split("@uninorte.edu.co");            
            File temp = new File("files\\"+name[0]);
            if(temp.exists()){
                try {
                    temp = new File("files\\"+name[0]+"\\"+name[0]+"_info.txt");
                    NodeBS root = NodeBS.fileToTree(temp);
                    Mostrar m = new Mostrar(root,name[0]);
                    current= this;
                    m.setVisible(true);
                    current.setVisible(false);
                } catch (Exception ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else{
                current = this;
                this.setVisible(false);
                StartProyect sp = new StartProyect(name[0]);
                sp.setVisible(true);
                
            }
            
        }
    }//GEN-LAST:event_observarBMouseClicked

    private void generarTxtBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generarTxtBMouseClicked
        String [] temporal = flagSession.getText().split("@uninorte.edu.co");            
        File tempo = new File("files\\"+temporal[0]);
        if(generarTxtB.isEnabled() && tempo.exists()){
            JFileChooser jf =  new JFileChooser();
            jf.setDialogTitle("Seleccione donde guardará");
            if(jf.showSaveDialog(this) == JFileChooser.APPROVE_OPTION){
                String path = jf.getSelectedFile().getAbsolutePath();
                System.out.println("hi: "+path);
                try {
                    path +=".txt";
                    String [] name = flagSession.getText().split("@uninorte.edu.co");
                    File f = new File(path);
                    File temp = new File("files\\"+name[0]+"\\"+name[0]+".txt");
                    Archivos.copyFile(temp, f);
                    JOptionPane.showMessageDialog(this,"El archivo ha sido guardado en "+path,
                            "Creacion exitosa", JOptionPane.INFORMATION_MESSAGE);
                } catch (IOException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }   
            }
        }
        else if (generarTxtB.isEnabled()){
            JOptionPane.showMessageDialog(null,"Aun no se ha creado ningun proyecto",
                    "No existe archivo",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_generarTxtBMouseClicked

    private void reporteBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reporteBMouseClicked
        if(reporteB.isEnabled()){
            String name = flagSession.getText().split("@uninorte.edu.co")[0];
            File temp = new File("files\\"+name);
            if(temp.exists()){
                try {
                    temp = new File("files\\"+name+"\\"+name+"_info.txt");
                    NodeBS root = NodeBS.fileToTree(temp);
                    Reporte r = new Reporte(root,name);
                    current= this;
                    r.setVisible(true);
                    current.setVisible(false);
                } catch (Exception ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else{
                current = this;
                this.setVisible(false);
                StartProyect sp = new StartProyect(name);
                sp.setVisible(true);
                
            }
        }
    }//GEN-LAST:event_reporteBMouseClicked

    private void cerrarSesionBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionBActionPerformed
        JOptionPane.showMessageDialog(null,"Ha cerrado sesión correctamente",
                "Cerrar sesión", JOptionPane.INFORMATION_MESSAGE);
        loginActions("No ha iniciado sesión", false);

    }//GEN-LAST:event_cerrarSesionBActionPerformed

    /**
     * Esta subrutina se encarga de cambiar los valores para un usuario cuando 
     * inicia sesión y cuando cierra sesión
     * @param user usuario
     * @param flag true si inicia, false si cierra sesión
     */
    
    private void loginActions(String user, boolean flag) {
        flagSession.setText(user);
        agregarTareaB.setEnabled(flag);
        observarB.setEnabled(flag);
        reporteB.setEnabled(flag);
        generarTxtB.setEnabled(flag);
        mailField.setEditable(!flag);
        passField.setEditable(!flag);
        loginButton.setEnabled(!flag);
        registrarseLabel.setEnabled(!flag);
        logged = flag;
        cerrarSesionB.setEnabled(flag);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agregarTareaB;
    private javax.swing.JLabel cerrarButton;
    private javax.swing.JButton cerrarSesionB;
    private javax.swing.JLabel flagSession;
    private javax.swing.JLabel generarTxtB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel jpIngreso;
    private javax.swing.JLabel lblInternet;
    private javax.swing.JLabel lblMusica;
    private javax.swing.JButton loginButton;
    private javax.swing.JTextField mailField;
    private javax.swing.JLabel minimizarButton;
    private javax.swing.JLabel observarB;
    private javax.swing.JPasswordField passField;
    private javax.swing.JLabel registrarseLabel;
    private javax.swing.JLabel reporteB;
    // End of variables declaration//GEN-END:variables
}
