/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Grafo;

import View.NodeBS;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.time.LocalDate;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author fazd
 */
public class DrawGraph extends javax.swing.JFrame {

    private MyArray nodes;
    private MyArray edges;
    private MyArray visited;
    private MyArray adj;
    private Graphics graphic;
    private int cont;
    private NodeBS root;
    public static JFrame frame;
    
    
    public DrawGraph(Grafo g, NodeBS root){
        initComponents();
        this.nodes = g.getNodos();
        this.edges = g.getAristas();
        graphic = panel.getGraphics();
        numero.setText(""+nodes.size());
        cont=0;
        this.root = root;
    }
    
    
    public DrawGraph() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        depen = new javax.swing.JButton();
        panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        numero = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        report = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        primeraact = new javax.swing.JLabel();
        ultimaact = new javax.swing.JLabel();
        precioT = new javax.swing.JLabel();
        Atrás = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        depen.setBackground(new java.awt.Color(255, 255, 255));
        depen.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        depen.setText("dependencias");
        depen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depenActionPerformed(evt);
            }
        });

        panel.setBackground(new java.awt.Color(238, 112, 82));
        panel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelMouseMoved(evt);
            }
        });
        panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel1.setText("Cantidad de nodos");

        numero.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        numero.setText("numero");

        report.setColumns(20);
        report.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        report.setRows(5);
        jScrollPane1.setViewportView(report);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel2.setText("Reporte ");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel3.setText("Primera act");

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel6.setText("Ultima act");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel7.setText("Precio total");

        Atrás.setBackground(new java.awt.Color(255, 255, 255));
        Atrás.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        Atrás.setText("Atrás");
        Atrás.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrásActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel4.setText("GRAFO");

        jLabel5.setText("Reporte de finalización");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jLabel4)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3))
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(primeraact, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(precioT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ultimaact, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Atrás, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(numero)
                            .addComponent(depen))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jScrollPane1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numero)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(depen)
                                .addGap(73, 73, 73))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addComponent(jLabel2)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(primeraact, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(ultimaact, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(precioT, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Atrás)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Esta subrutina se encarga de calcular las fechas y parte del reporte del grafo
     */
    
    
    private void calcFechas(){
        int i = 0;
        LocalDate fecha =this.root.getFechaInicio();
        LocalDate maximo = null;
        LocalDate minimo = null;
        NodeBS max = null;
        NodeBS min = null;
        int total = 0;
        while(i < nodes.size()){
            Nodo n = (Nodo) nodes.get(i);
            NodeBS nodo = n.getNodo();
            nodo.setFechaInicio(root);
            total+= nodo.getBudget();
            if(i==0){
                maximo = minimo = nodo.getFechaInicio();
                max = min = nodo;
            }
            if(maximo.isBefore(nodo.getFechaInicio())){
                maximo = nodo.getFechaInicio();
                max = nodo;
            }
            if(minimo.isAfter(nodo.getFechaInicio())){
                minimo = nodo.getFechaInicio();
                min = nodo;
            }
            i++;
        }
        primeraact.setText(min.getNombre());
        ultimaact.setText(max.getNombre());
        precioT.setText(""+total);
    }
    
    /**
     * subrutina que se encarga de calcular y mostrar el reporte del grafo
     */
    
    private void reporte (){
        int index = 0;
        String text="";
        calcFechas();
        while(index < nodes.size()){
            Nodo n = (Nodo) nodes.get(index);
            //System.out.println("found: "+ n.getNombre());
            NodeBS nodo = n.getNodo();
            text+= nodo.getNombre()+"\n";
            text+="Fecha de inicio: "+nodo.getFechaInicio().minusDays(nodo.getTime())+"\n";
            text+="Fecha de Finalización: "+nodo.getFechaInicio()+"\n";
            report.setText(text);
            index++;
        }
    }
    
    
    private void depenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depenActionPerformed
        int index = 0;
        while(index < nodes.size()){
            Nodo n = (Nodo) nodes.get(index);
            //System.out.println("found: "+ n.getNombre());
            NodeBS nodo = n.getNodo();
            String str = nodo.getDep();
            //System.out.println(str);
            if(!str.equals("")){
                String dep [] = str.split(",");
                for(int i = 0; i < dep.length; i++){
                    Nodo temp = MyArray.find(nodes, dep[i]);
                    NodeBS tempBS = temp.getNodo();
                    //ArrowHead.drawArrowHead(graphic, tempBS.getX(), nodo.getX(), 
                    //        tempBS.getY(), nodo.getY());
                    graphic.drawLine(nodo.getX(), nodo.getY(), tempBS.getX(),
                            tempBS.getY());
                }
            }
            index++;
        }
        
        reporte();
        
        
    }//GEN-LAST:event_depenActionPerformed

    private void panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMouseClicked
        if(!numero.getText().equals("0")){
            int x = evt.getX()-20;
            int y = evt.getY() - 15;
            if(x>25 && y >25){
                Nodo n = (Nodo) nodes.get(cont);
                NodeBS nodoBS = n.getNodo();
                cont++;
                nodoBS.setX(x);
                nodoBS.setY(y);
                graphic.fillOval(x, y, 25, 25);
                char [] arr = (n.getNombre()).toCharArray();
                graphic.drawChars(arr, 0, arr.length, x, y);
                int num = Integer.parseInt(numero.getText());
                num--;
                numero.setText(""+num);
            }
            else{
                JOptionPane.showMessageDialog(this,"Por favor escoja otro sitio"
                        ,"Error",JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(this,"Ya no puede agregar mas nodos", "Error"
                    , JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_panelMouseClicked

    private void panelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMouseMoved
    }//GEN-LAST:event_panelMouseMoved

    private void AtrásActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrásActionPerformed
        this.setVisible(false);
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AtrásActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DrawGraph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DrawGraph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DrawGraph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DrawGraph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DrawGraph().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atrás;
    private javax.swing.JButton depen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel numero;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel precioT;
    private javax.swing.JLabel primeraact;
    private javax.swing.JTextArea report;
    private javax.swing.JLabel ultimaact;
    // End of variables declaration//GEN-END:variables
}
